version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/chatbot
    networks:
      - app-network
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=chatbot
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local